# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 11:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_resource_price'),
    ]

    def forwards(apps, schema_editor):
        Resource = apps.get_model('base', 'Resource')
        for row in Resource.objects.all():
            row.save()
        Event = apps.get_model('base', 'Event')
        for row in Event.objects.all():
            row.save()

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date',), 'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from=b'title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from=b'name', unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=False, populate_from=b'title', unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=False, populate_from=b'name', unique=True),
        ),

    ]
