# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_slug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 15, 13, 17, 16, 843451, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='modified',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 3, 15, 13, 17, 24, 907510, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
    ]
