# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contact_created_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Contact', verbose_name='instructor'),
        ),
    ]
