# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 14:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
        ('base', '0005_training_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='image'),
        ),
    ]
