# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Contact', verbose_name='instructor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, to='base.Contact'),
        ),
    ]
