# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_add_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=30, verbose_name='title'),
        ),
    ]
