# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_resource_type_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='unit_rounding',
            field=models.FloatField(default=1.0, verbose_name='unit rounding'),
        ),
    ]
