# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_fix_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, verbose_name='iban')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='transaction id')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('type', models.CharField(choices=[(b'DBIT', 'Debit'), (b'CRDT', 'Credit')], default=b'CRDT', max_length=4, verbose_name='type')),
                ('booking_date', models.DateField(verbose_name='booking date')),
                ('raw_text', models.TextField(blank=True, verbose_name='raw text')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('counterpart_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='counterpart account')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Invoice', verbose_name='invoice')),
            ],
            options={
                'ordering': ('-booking_date',),
                'verbose_name': 'bank transaction',
                'verbose_name_plural': 'bank transactions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together=set([('iban', 'transaction_id')]),
        ),
    ]
