# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_resource_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('payload', models.TextField(blank=True, verbose_name='payload')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logentries', to='base.Contact', verbose_name='owner')),
            ],
            options={
                'ordering': ('-timestamp',), 'verbose_name': 'log entry', 'verbose_name_plural': 'log entries'
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='token')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='description')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='base.Contact', verbose_name='owner')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='logentry',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logentries', to='nfc.Token', verbose_name='token'),
        ),
    ]
